

all:
	mvn compile

small_grid:
	mvn exec:java -Dexec.mainClass="myProj.GridSmall"

small_plot:
	mvn exec:java -Dexec.mainClass="myProj.PlotSmall"


lander:
	mvn exec:java -Dexec.mainClass="myProj.Lander"


mtcar:
	mvn exec:java -Dexec.mainClass="myProj.MtnCarTest"